### ISSUE TITLE
在 rails 3.0, ruby 1.9.1 环境下, 使用 bundle 安装报错

### ISSUE THREAD

**Issue by mambahao** [elvuel/hz2py#2]
Installing hz2py (0.0.3) /opt/local/lib/ruby1.9/1.9.1/rubygems/specification.rb:803:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError

**Comment by elvuel** [comment]
Thanks @mambahao :). 0.3版本在1.9下确有问题，现用ruby19已重新release了。
